---
AllCops:
  DisplayCopNames: true
  Exclude: 
    - "db/*"
    - "config/**/*"
    - "bin/**/*"
    - "script/*"
    - "spec/*_helper.rb"
    - "features/support/env.rb"
    - "db/migrate/*"
    - "lib/tasks/*"
    - "scripts/*"
    - "install/**/*"
Style/Documentation:
  Enabled: false
