---
- name: Ensure common packages are installed
  become: true
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - python-pycurl
  tags: postgres_common

- name: Include Debian tasks
  include: debian.yml
  when: ansible_os_family == "Debian"
  tags: postgres_debian

- name: Ensure apt cache is up to date
  become: true
  apt: update_cache=yes cache_valid_time=3600
  tags: postgres_debian

- name: Ensure packages are installed
  become: true
  apt: pkg={{ item }}
  with_items:
    - postgresql-{{ pg_version }}
    - postgresql-client-{{ pg_version }}
    - python-psycopg2
  register: db_setup
  environment: '{{ pg_proxy_env }}'
  tags: postgres_packages

- name: Recreate cluster
  include: recreate_cluster.yml
  when: pg_cluster_recreate
  tags: postgres_cluster

- name: Update pg_hba.conf file
  become: true
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/{{ pg_version }}/{{ pg_cluster }}/pg_hba.conf owner={{ pg_admin_user }} group={{ pg_admin_user }} mode=0640
  notify: restart postgresql
  tags: postgres_config

- name: Update postgres.conf file
  become: true
  template: src=master.conf.j2 dest=/etc/postgresql/{{ pg_version }}/{{ pg_cluster }}/postgresql.conf owner={{ pg_admin_user }} group={{ pg_admin_user }} mode=0644
  notify: restart postgresql
  tags: postgres_config

- name: Ensure ssl cert permissions
  become: true
  file:
    path="{{ pg_cfg_srv_ssl_cert_file }}"
    owner="{{ pg_admin_user }}"
    group="{{ pg_admin_user }}"
    mode="0600"
  when: pg_cfg_srv_ssl_cert_file is defined
  tags: postgres_config

- name: Ensure ssl key permissions
  become: true
  file:
    path="{{ pg_cfg_srv_ssl_key_file }}"
    owner="{{ pg_admin_user }}"
    group="{{ pg_admin_user }}"
    mode="0600"
  when: pg_cfg_srv_ssl_key_file is defined
  tags: postgres_config

- include: extensions_common.yml
  tags: postgres_extensions

- meta: flush_handlers

- name: ensure postgresql server is started
  become: true
  service:
    name: postgresql
    state: started
    enabled: yes
    arguments: "{{ pg_version }}"
    pattern: "/usr/lib/postgresql/{{ pg_version | float }}/bin/postgres -D /var/lib/postgresql/{{ pg_version }}/{{ pg_cluster }}"
  tags: postgres_start

- include: postgis.yml
  when: pg_postgis
  tags: postgres_postgis
